################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3001

################################################################################
##                               Database options                             ##
################################################################################
database:
  host: "${DATABASE_HOST}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  database: "${DATABASE_NAME}"
  scheme: "${DATABASE_SCHEME}"
  port: "${DATABASE_PORT}"
  connectionTimeoutMillis: 2000
  max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: debug

node:
  interval: 5
  max_txs: 8
  send_interval: 1
  ipfs_api_url: http://localhost:5001
  ipfs_gateway_url: http://localhost:8080
  ipfs_test: true

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      expression: "*/1 * * * * *"
    - name: send_block
      enable: true
      expression: "*/1 * * * * *"

contracts:
  publisherKey: "${PUBLISHER_KEY}"
  purchaseAddress: "0x0000000000000000000000000000000000000000"

setting:
  accessKey:
    - key: "${ACCESS_KEY0}"
      sender: "${SENDER0}"
      waiting: "${WAITING0}"
    - key: "${ACCESS_KEY1}"
      sender: "${SENDER1}"
      waiting: "${WAITING1}"
  purchaseSigners:
    - sender: "${SENDER0}"
      collectors:
        - "${COLLECTOR0}"
      delegate: "${DELEGATE_KEY0}"
    - sender: "${SENDER1}"
      collectors:
        - "${COLLECTOR1}"
      delegate: "${DELEGATE_KEY1}"
  relayEndpoint: "${RELAY_ENDPOINT}"
  relayAccessKey: "${RELAY_ACCESS_KEY}"
  smsEndpoint: "${SMS_ENDPOINT}"
  smsAccessKey: "${SMS_ACCESS_KEY}"
  messageEnable: "${MESSAGE_ENABLE}"
  allowedShopIdPrefix: "0x0001"
